# Use the official Node.js image as the base image
FROM node:latest AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY tsfrontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY tsfrontend ./

# Production environment
ENV NODE_ENV=production
ENV PORT=3000

# Build the application
RUN npm run build



# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

