FROM python:3.11.9-bookworm

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY config.py  /app/config.py
COPY jobs       /app/jobs
COPY prompts    /app/prompts
COPY utils      /app/utils
COPY ontologies /app/ontologies

WORKDIR /app
ENTRYPOINT [ "python", "jobs/scheduler.py" ]
